### ISSUE TITLE
Prettify css props / Aligning prefix

### ISSUE THREAD

**Issue by M-ZubairAhmed** [ansumanshah/css-in-js#9]
I would like to propose the following 
1. Aligning prefix in same order
![image](https://user-images.githubusercontent.com/17708702/30053301-eccad624-9245-11e7-8592-69a21c4e7bb9.png)

Any ideas or suggestions for improvements

**Comment by ansumanshah** [comment]
1. isn't it better to align all prefix related to direction/flex-direction together rather than aligning prefix types, so that we can remove/add them easily depending on the property??
```
-webkit-box-direction: normal;
-moz-box-direction: normal;

-webkit-box-orient: horizontal;
-moz-box-orient: horizontal;
```
2. most of the current build tools support autoprefixing by default / with a plugin what other use cases shall this cater to?

**Comment by M-ZubairAhmed** [comment]
thats a good point right now i cannot think of a use case. But do you think giving the developer choice to do that is a good idea i.e aligning common prefixes together. Also how about having assigning each property an order 
example 
display always showing up first and so on..
